name: Publish 🐳 to DockerHub

on:
  push:
    tags:
      - "v*"

env:
  alpine_version: alpine3.12
  debian_version: buster

jobs:
  build-n-publish-dockerhub:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [alpine, debian]

    steps:
      - uses: actions/checkout@v2

      - name: Wait on all tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          check-regexp: (test.*|black)

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install packaging
#      - name: Skip if this is not a final release
#        shell: python
#        run: |
#          import sys
#          from packaging.version import parse
#          version_file = open("version", "r")
#          version = version_file.readline().strip()
#          parsed_version = parse(version)
#          if parsed_version.is_prerelease:
#              print("This is a pre- and/or dev- release - skipping publish!")
#              sys.exit(1)
#          else:
#              print("This is a final release - continuing with publish.")
#      - name: Publish to DockerHub
#        env:
#          os: ${{ matrix.os }}
#          docker_username: ${{ secrets.DOCKER_USERNAME }}
#          docker_password: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          ./dev/build_docker_images.sh
