name: Publish 🐍 to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-n-publish-pypi:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Wait on all tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          check-regexp: (test.*|black)

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc
          pip install pypandoc
      - name: Build
        run: |
          python setup.py build sdist bdist_wheel
#      - name: Publish distribution 📦 to PyPI
#        uses: pypa/gh-action-pypi-publish@v1.4.1
#        with:
#          password: ${{ secrets.PYPI_API_TOKEN }}
